# Generated by Django 5.2.7 on 2025-10-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
