# Generated by Django 5.2.7 on 2025-10-23 06:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_rating_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.CharField(default='Fun Match', max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
