# Generated by Django 5.2.7 on 2025-10-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_rating_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='facilities',
            field=models.TextField(blank=True, help_text='Enter facilities separated by commas (e.g., Wifi, AC, Toilet)', null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='image_url_2',
            field=models.URLField(blank=True, null=True, verbose_name='Gallery Image 2 URL'),
        ),
        migrations.AddField(
            model_name='venue',
            name='image_url_3',
            field=models.URLField(blank=True, null=True, verbose_name='Gallery Image 3 URL'),
        ),
        migrations.AddField(
            model_name='venue',
            name='image_url_4',
            field=models.URLField(blank=True, null=True, verbose_name='Gallery Image 4 URL'),
        ),
        migrations.AddField(
            model_name='venue',
            name='image_url_5',
            field=models.URLField(blank=True, null=True, verbose_name='Gallery Image 5 URL'),
        ),
        migrations.AddField(
            model_name='venue',
            name='price_range',
            field=models.CharField(blank=True, help_text='e.g., 100.000 - 300.000', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Main Image URL'),
        ),
    ]
