# Generated by Django 5.2.7 on 2025-10-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_events_price_events_type_alter_events_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.CharField(choices=[('Fun Match', 'Fun Match'), ('Turnamen', 'Turnamen'), ('Sparring', 'Sparring'), ('Lainnya', 'Lainnya')], default='Fun Match', max_length=50),
        ),
    ]
