# Generated by Django 5.2.7 on 2025-10-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_venue_facilities_venue_image_url_2_venue_image_url_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='price_range',
        ),
        migrations.AddField(
            model_name='venue',
            name='max_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Price (IDR)'),
        ),
        migrations.AddField(
            model_name='venue',
            name='min_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Price (IDR)'),
        ),
    ]
