# Generated by Django 5.2.7 on 2025-10-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_events_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.CharField(choices=[('Fun Match', 'Fun Match'), ('Turnamen', 'Turnamen')], default='Fun Match', max_length=50),
        ),
    ]
