# Generated by Django 5.2.7 on 2025-10-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_venue_price_range_venue_max_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='min_price',
        ),
        migrations.AddField(
            model_name='venue',
            name='price_range',
            field=models.CharField(blank=True, help_text='e.g., 100.000 - 300.000', max_length=100, null=True),
        ),
    ]
