# Generated by Django 5.2.7 on 2025-10-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_events_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Beginner Guides', 'Beginner Guides'), ('Technique & Strategy', 'Technique & Strategy'), ('Fitness & Warm-Ups', 'Fitness & Warm-Ups'), ('Coaching Insights', 'Coaching Insights')], default='Beginner Guides', max_length=50),
        ),
    ]
